// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-vue-admin/internal/app/system/dao/internal"
)

// internalGenTableDao is internal type for wrapping internal DAO implements.
type internalGenTableDao = *internal.GenTableDao

// genTableDao is the data access object for table gen_table.
// You can define custom methods on it to extend its functionality as you wish.
type genTableDao struct {
	internalGenTableDao
}

var (
	// GenTable is globally public accessible object for table gen_table operations.
	GenTable = genTableDao{
		internal.NewGenTableDao(),
	}
)

// Fill with you ideas below.
