// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-vue-admin/internal/app/system/dao/internal"
)

// internalSysNoticeDao is internal type for wrapping internal DAO implements.
type internalSysNoticeDao = *internal.SysNoticeDao

// sysNoticeDao is the data access object for table sys_notice.
// You can define custom methods on it to extend its functionality as you wish.
type sysNoticeDao struct {
	internalSysNoticeDao
}

var (
	// SysNotice is globally public accessible object for table sys_notice operations.
	SysNotice = sysNoticeDao{
		internal.NewSysNoticeDao(),
	}
)

// Fill with you ideas below.
