// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysUserOnline is the golang structure for table sys_user_online.
type SysUserOnline struct {
	SessionId      string      `json:"sessionId"      description:"用户会话id"`
	LoginName      string      `json:"loginName"      description:"登录账号"`
	DeptName       string      `json:"deptName"       description:"部门名称"`
	Ipaddr         string      `json:"ipaddr"         description:"登录IP地址"`
	LoginLocation  string      `json:"loginLocation"  description:"登录地点"`
	Browser        string      `json:"browser"        description:"浏览器类型"`
	Os             string      `json:"os"             description:"操作系统"`
	Status         string      `json:"status"         description:"在线状态on_line在线off_line离线"`
	StartTimestamp *gtime.Time `json:"startTimestamp" description:"session创建时间"`
	LastAccessTime *gtime.Time `json:"lastAccessTime" description:"session最后访问时间"`
	ExpireTime     int         `json:"expireTime"     description:"超时时间，单位为分钟"`
}
