// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysUserOnline is the golang structure of table sys_user_online for DAO operations like Where/Data.
type SysUserOnline struct {
	g.Meta         `orm:"table:sys_user_online, do:true"`
	SessionId      interface{} // 用户会话id
	LoginName      interface{} // 登录账号
	DeptName       interface{} // 部门名称
	Ipaddr         interface{} // 登录IP地址
	LoginLocation  interface{} // 登录地点
	Browser        interface{} // 浏览器类型
	Os             interface{} // 操作系统
	Status         interface{} // 在线状态on_line在线off_line离线
	StartTimestamp *gtime.Time // session创建时间
	LastAccessTime *gtime.Time // session最后访问时间
	ExpireTime     interface{} // 超时时间，单位为分钟
}
