// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/template-single/internal/app/service/internal/dao/internal"
)

// genTableDao is the data access object for table gen_table.
// You can define custom methods on it to extend its functionality as you wish.
type genTableDao struct {
	*internal.GenTableDao
}

var (
	// GenTable is globally public accessible object for table gen_table operations.
	GenTable = genTableDao{
		internal.NewGenTableDao(),
	}
)

// Fill with you ideas below.