// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/template-single/internal/app/service/internal/dao/internal"
)

// genTableColumnDao is the data access object for table gen_table_column.
// You can define custom methods on it to extend its functionality as you wish.
type genTableColumnDao struct {
	*internal.GenTableColumnDao
}

var (
	// GenTableColumn is globally public accessible object for table gen_table_column operations.
	GenTableColumn = genTableColumnDao{
		internal.NewGenTableColumnDao(),
	}
)

// Fill with you ideas below.