// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/template-single/internal/app/service/internal/dao/internal"
)

// sysUserOnlineDao is the data access object for table sys_user_online.
// You can define custom methods on it to extend its functionality as you wish.
type sysUserOnlineDao struct {
	*internal.SysUserOnlineDao
}

var (
	// SysUserOnline is globally public accessible object for table sys_user_online operations.
	SysUserOnline = sysUserOnlineDao{
		internal.NewSysUserOnlineDao(),
	}
)

// Fill with you ideas below.