// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/template-single/internal/app/service/internal/dao/internal"
)

// sysJobLogDao is the data access object for table sys_job_log.
// You can define custom methods on it to extend its functionality as you wish.
type sysJobLogDao struct {
	*internal.SysJobLogDao
}

var (
	// SysJobLog is globally public accessible object for table sys_job_log operations.
	SysJobLog = sysJobLogDao{
		internal.NewSysJobLogDao(),
	}
)

// Fill with you ideas below.