// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/template-single/internal/app/service/internal/dao/internal"
)

// sysOperLogDao is the data access object for table sys_oper_log.
// You can define custom methods on it to extend its functionality as you wish.
type sysOperLogDao struct {
	*internal.SysOperLogDao
}

var (
	// SysOperLog is globally public accessible object for table sys_oper_log operations.
	SysOperLog = sysOperLogDao{
		internal.NewSysOperLogDao(),
	}
)

// Fill with you ideas below.