// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"go-vue-admin/internal/app/system/model/entity"
)

type (
	ISysDictData interface {
		GetDictDataByType(ctx context.Context, dictType string) (dictdata []*entity.SysDictData, err error)
	}
)

var (
	localSysDictData ISysDictData
)

func SysDictData() ISysDictData {
	if localSysDictData == nil {
		panic("implement not found for interface ISysDictData, forgot register?")
	}
	return localSysDictData
}

func RegisterSysDictData(i ISysDictData) {
	localSysDictData = i
}
