// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"go-vue-admin/internal/app/system/model"
	"go-vue-admin/internal/app/system/model/entity"
)

type (
	IUser interface {
		Create(ctx context.Context, in model.UserCreateInput) (err error)
		IsSignedIn(ctx context.Context) bool
		Login(ctx context.Context, in model.UserSignInInput) (err error)
		LogOut(ctx context.Context) error
		IsUserNameAvailable(ctx context.Context, UserName string) (bool, error)
		IsNicknameAvailable(ctx context.Context, nickname string) (bool, error)
		GetProfile(ctx context.Context) *entity.SysUser
	}
)

var (
	localUser IUser
)

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
