# CLI.
gfcli:
  gen:
    dao:
      - link:            "mysql:root:123456@tcp(127.0.0.1:3306)/gvadmindb"
        tables:          ""
        tablesEx:        ""
        removePrefix:    "gf_"
        descriptionTag:  true
        noModelComment:  true
        path: "./internal/app"
    service:
      srcFolder: "./internal/app"