// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-03-27 22:21:57
// =================================================================================

package do

import(
"github.com/gogf/gf/v2/frame/g"
"github.com/gogf/gf/v2/os/gtime"
)

// SysMenu is the golang structure of table sys_menu for DAO operations like Where/Data.
type SysMenu struct {
g.Meta `orm:"table:sys_menu, do:true"`
    MenuId interface{} // 菜单ID                                    
    MenuName interface{} // 菜单名称                                  
    ParentId interface{} // 父菜单ID                                  
    OrderNum interface{} // 显示顺序                                  
    Url interface{} // 请求地址                                  
    Target interface{} // 打开方式（menuItem页签 menuBlank新窗口）  
    MenuType interface{} // 菜单类型（M目录 C菜单 F按钮）             
    Visible interface{} // 菜单状态（0显示 1隐藏）                   
    IsRefresh interface{} // 是否刷新（0刷新 1不刷新）                 
    Perms interface{} // 权限标识                                  
    Icon interface{} // 菜单图标                                  
    CreateBy interface{} // 创建者                                    
    CreateTime *gtime.Time // 创建时间                                  
    UpdateBy interface{} // 更新者                                    
    UpdateTime *gtime.Time // 更新时间                                  
    Remark interface{} // 备注                                      
}