// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-03-27 22:21:57
// =================================================================================

package entity



// SysRoleMenu is the golang structure for table sys_role_menu.
type SysRoleMenu struct {
    RoleId int64 `json:"roleId" description:"角色ID"`  
    MenuId int64 `json:"menuId" description:"菜单ID"`  
}