// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-03-27 22:21:57
// =================================================================================

package entity



// SysRoleDept is the golang structure for table sys_role_dept.
type SysRoleDept struct {
    RoleId int64 `json:"roleId" description:"角色ID"`  
    DeptId int64 `json:"deptId" description:"部门ID"`  
}