// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-03-27 22:21:57
// =================================================================================

package entity

import(
"github.com/gogf/gf/v2/os/gtime"
)

// SysMenu is the golang structure for table sys_menu.
type SysMenu struct {
    MenuId     int64       `json:"menuId"     description:"菜单ID"`                                    
    MenuName   string      `json:"menuName"   description:"菜单名称"`                                  
    ParentId   int64       `json:"parentId"   description:"父菜单ID"`                                  
    OrderNum   int         `json:"orderNum"   description:"显示顺序"`                                  
    Url        string      `json:"url"        description:"请求地址"`                                  
    Target     string      `json:"target"     description:"打开方式（menuItem页签 menuBlank新窗口）"`  
    MenuType   string      `json:"menuType"   description:"菜单类型（M目录 C菜单 F按钮）"`             
    Visible    string      `json:"visible"    description:"菜单状态（0显示 1隐藏）"`                   
    IsRefresh  string      `json:"isRefresh"  description:"是否刷新（0刷新 1不刷新）"`                 
    Perms      string      `json:"perms"      description:"权限标识"`                                  
    Icon       string      `json:"icon"       description:"菜单图标"`                                  
    CreateBy   string      `json:"createBy"   description:"创建者"`                                    
    CreateTime *gtime.Time `json:"createTime" description:"创建时间"`                                  
    UpdateBy   string      `json:"updateBy"   description:"更新者"`                                    
    UpdateTime *gtime.Time `json:"updateTime" description:"更新时间"`                                  
    Remark     string      `json:"remark"     description:"备注"`                                      
}