// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-03-27 22:21:57
// =================================================================================

package entity



// SysUserRole is the golang structure for table sys_user_role.
type SysUserRole struct {
    UserId int64 `json:"userId" description:"用户ID"`  
    RoleId int64 `json:"roleId" description:"角色ID"`  
}